//
//  ObjCViewController.m
//  AsynAwaitDemo
//
//  Created by Michael Maguire on 3/22/23.
//

#import "ObjCViewController.h"
#import <AsynAwaitDemo-Swift.h>

@implementation ObjCViewController

- (void)viewDidLoad {
    [super viewDidLoad];
    
    [Utility performWithCallbackWithCompletionHandler:^(Something * _Nullable something, NSError * _Nullable error) {
        if (error != nil) {
            NSLog(@"%@", [error localizedDescription]);
        } else {
            NSLog(@"%@", something);
        }
    }];
    
    //same as above, automagically generated by swift-obj-c bridge
    [Utility performAsyncAwaitWithCompletionHandler:^(Something * _Nullable something, NSError * _Nullable error) {
        if (error != nil) {
            NSLog(@"%@", [error localizedDescription]);
        } else {
            NSLog(@"%@", something);
        }
    }];
    
    //same as above, automagically generated by swift-obj-c bridge
    [Utility performAsyncAwaitThrowingWithCompletionHandler:^(Something * _Nullable something, NSError * _Nullable error) {
        if (error != nil) {
            NSLog(@"%@", [error localizedDescription]);
        } else {
            NSLog(@"%@", something);
        }
    }];
}

@end
